CREATE TABLE USUARIO(
	ID				UNIQUEIDENTIFIER		NOT NULL,
	NOME				NVARCHAR (150)			NOT NULL,
	EMAIL				NVARCHAR (100)			NOT NULL UNIQUE,
	SENHA				NVARCHAR (40)			NOT NULL,
	DATAHORACRIACAO			DATETIME			NOT NULL,
	PRIMARY KEY(ID))

	GO


CREATE TABLE CATEGORIA (
    	ID       		UNIQUEIDENTIFIER 	NOT NULL,
    	DESCRICAO 		NVARCHAR (50)    	NOT NULL,
    	PRIMARY KEY(ID))

	GO














CREATE TABLE CLIENTE (
    	ID         	UNIQUEIDENTIFIER 		NOT NULL,
    	NOME            NVARCHAR (150)   		NOT NULL,
    	CPF		NVARCHAR (15)    		NOT NULL,
   	MATRICULA   	NVARCHAR (15)    		NOT NULL,
    	DATA        	DATE             		NOT NULL,
    	IDADE      	NVARCHAR (3)     		NOT NULL,
    	CIVIL       	NVARCHAR (10)    		NOT NULL,
    	CEP        	NVARCHAR (10)    		NOT NULL,
	ENDERECO	NVARCHAR (150)			NOT NULL,
    	ESTADO      	NVARCHAR (3)     		NOT NULL,
    	MUNICIPIO   	NVARCHAR (20)    		NOT NULL,
    	BAIRRO      	NVARCHAR (30)    		NOT NULL,
    	TELEFONE    	NVARCHAR (14)    		NOT NULL,
    	CELULAR     	NVARCHAR (14)    		NOT NULL,
    	EMAIL      	NVARCHAR (40)    		NOT NULL,
    	OBSERVACOES 	NVARCHAR (500)   		NOT NULL,
    	SALARIO     	DECIMAL (18, 2)  		NOT NULL,
    	CATEGORIAID 	UNIQUEIDENTIFIER 		NOT NULL,
    	USUARIOID   	UNIQUEIDENTIFIER 		NOT NULL,
    	PRIMARY KEY 	(ID),
    	FOREIGN KEY 	(CATEGORIAID) REFERENCES CATEGORIA (ID),
    	FOREIGN KEY 	(USUARIOID) REFERENCES USUARIO (ID))